module.exports = {
  name: '佛山智慧云图管理后台',
  footerText: '佛山智慧云图管理后台 @ 2017 CORE',
  logo: '/logo.png',
  menus: [
    {
      id: 1,
      icon: 'laptop',
      name: '宽带地图',
    },
    {
      id: 11,
      bpid: 1,
      mpid: 1,
      icon: 'laptop',
      name: '基础数据管理',
      router: '/map/manage',
    },
    {
      id: 12,
      bpid: 1,
      mpid: 1,
      icon: 'laptop',
      name: '基础数据导入',
      router: '/map/import',
    },
    {
      id: 13,
      bpid: 1,
      mpid: 1,
      icon: 'laptop',
      name: '专题管理',
      router: '/map/zt',
    },
    {
      id: 14,
      bpid: 1,
      mpid: 1,
      icon: 'laptop',
      name: '详情管理',
      router: '/map/detail',
    },
    {
      id: 15,
      bpid: 1,
      mpid: 1,
      icon: 'laptop',
      name: '版块管理',
      router: '/map/plate',
    },
    {
      id: 16,
      bpid: 14,
      mpid: -1,
      icon: 'laptop',
      name: '详情列表',
      router: '/map/detail/:type/:id',
    },
    {
      id: 2,
      icon: 'team',
      name: '公共服务',
    },
    {
      id: 21,
      bpid: 2,
      mpid: 2,
      icon: 'team',
      name: '基础数据管理',
      router: '/public/manage',
    },
    {
      id: 22,
      bpid: 2,
      mpid: 2,
      icon: 'team',
      name: '基础数据导入',
      router: '/public/import',
    },
    {
      id: 23,
      bpid: 2,
      mpid: 2,
      icon: 'team',
      name: '专题管理',
      router: '/public/zt',
    },
    {
      id: 24,
      bpid: 2,
      mpid: 2,
      icon: 'team',
      name: '详情管理',
      router: '/public/detail',
    },
    {
      id: 25,
      bpid: 24,
      mpid: -1,
      icon: 'team',
      name: '详情列表',
      router: '/public/detail/:type/:id',
    },
    {
      id: 6,
      icon: 'layout',
      name: '服务评价管理',
    },    
    {
      id: 601,
      bpid: 6,
      mpid: 6,
      icon: 'layout',
      name: '宽带服务评价',
      router: '/evaluate/map/',
    },
    {
      id: 602,
      bpid: 6,
      mpid: 6,
      icon: 'layout',
      name: '公共服务评价',
      router: '/evaluate/public/',
    }, 
    {
      id: 603,
      bpid: 6,
      mpid: 6,
      icon: 'layout',
      name: '用户权限管理',
      router: '/evaluate/auth/',
    },
    {
      id: 604,
      bpid: 6,
      mpid: 6,
      icon: 'layout',
      name: '评价问题类型管理',
      router: '/evaluate/problem/',
    },                  
  ],
  city: [{
    value: 44,
    label: '广东省',
    children: [{
      value: 6,
      label: '佛山市',
      children: [
        {
          value: 1,
          label: '顺德区',
        },
        {
          value: 2,
          label: '高明区',
        },
        {
          value: 3,
          label: '三水区',
        },
        {
          value: 4,
          label: '南海区',
        },
        {
          value: 5,
          label: '禅城区',
        },
        {
          value: -1,
          label: '所有',
        },
      ],
    }],
  }],
  plate: {
    list: 'list',
    add: 'add',
  },
  openPages: ['/login'],
};
